### ISSUE TITLE
Linear Classifier on CIFAR10 with 1000 classes

### ISSUE THREAD

**Issue by pederismo** [abhinavagarwalla/swav-cifar10#1]
Hi,
I'm also trying to run experiments on CIFAR10 using SwAV and I came across your repository.
I have a question regarding this [line](https://github.com/abhinavagarwalla/swav-cifar10/blob/381b0662c82853e070c1b4fbc81e225047f5f9e5/eval_linear.py#L142) of eval_linear.py: I don't understand why you are keeping the number of output classes as 1000 as if it was still ImageNet, but I thought we were evaluating of CIFAR10. 
Maybe I'm missing something? Did you only ever train on CIFAR10 or did you also test this evaluation?

Thanks!

**Comment by adnan1306** [comment]
Did you understand the reason? @pederismo

**Comment by zyxforever** [comment]
> Hi, I'm also trying to run experiments on CIFAR10 using SwAV and I came across your repository. I have a question regarding this [line](https://github.com/abhinavagarwalla/swav-cifar10/blob/381b0662c82853e070c1b4fbc81e225047f5f9e5/eval_linear.py#L142) of eval_linear.py: I don't understand why you are keeping the number of output classes as 1000 as if it was still ImageNet, but I thought we were evaluating of CIFAR10. Maybe I'm missing something? Did you only ever train on CIFAR10 or did you also test this evaluation?
> 
> Thanks!

I have the same question with you, do you know the reason now?

**Comment by adnan1306** [comment]
No. But I was able to train on CFIAR10.
