### ISSUE TITLE
CIFAR-10 normalization

### ISSUE THREAD

**Issue by yqy2001** [abhinavagarwalla/swav-cifar10#2]
It seems that you are using the Imagenet's _mean_ and _std_ to normalize cifar10, which may lead to performance drop.

https://github.com/abhinavagarwalla/swav-cifar10/blob/381b0662c82853e070c1b4fbc81e225047f5f9e5/eval_linear.py#L110

**Comment by abhinavagarwalla** [comment]
Hi @yqy2001 
I just added the CIFAR-10 normalization parameters and a note which might be useful for someone using this repo. Thank you for bringing this to my attention!
